components/Progress/Progress.css, components/Progress/Progress.js, package.json, styleguide/sections/Forms.js, styleguide/webpack-dev.config.js
=> progress bar

components/Btn/Btn.js, components/EmailMultiInput/EmailMultiInput.js, components/FormInput/FormInput.css, components/FormInput/FormInput.js, components/LikeDislike/LikeDislike.js, components/Progress/Progress.css, components/Progress/Progress.js, components/SelectableInput/SelectableInput.css, globals/typography.css, package.json, styleguide/Styleguide.js, styleguide/sections/Buttons.js, styleguide/sections/Forms.js, styleguide/sections/Section.js, styleguide/styleguide.css, styleguide/webpack-dev.config.js, styleguide/webpack.config.js
- Stupid css-loader fix
- Change `Progress` classnames, add transition 
- Document `Progress` component
- `FormInput` component improvements & documentation
=> Fixes, features, improvements

components/Btn/Btn.css, components/Btn/Btn.js, components/Panel/Panel.css, components/Panel/Panel.js, globals/colours.css, globals/modifiers.css, styleguide/sections/Buttons.js, styleguide/sections/Panels.js
Includes: 
- Zero margin modifiers ie `ml0, mr0, m0`
- Full width buttons `<Btn fullWidth/>`
- Alert panels
overwrites #6
=> Zero margins, Alert panels, Full width buttons

.eslintrc, components/Slider/Slider.css, components/Slider/Slider.js, globals/colours.css, package.json, styleguide/sections/Forms.js
With ticks (in use on topnotes):
=> Add Slider component

components/Btn/Btn.css, components/Panel/Panel.js, globals/modifiers.css
Changed the clear button modifiers to match the designs
=> Clear button tweaks

components/Icon/Icon.css, components/Icon/icons.js, components/Icon/icons/card.svg, package.json
https://github.com/olahol/react-tagsinput/issues/43
=> New card icon & hard-set react-tagsinput version

components/Btn/Btn.css, components/FormInput/FormInput.css, components/HoverCard/HoverCard.js, globals/colours.css, styleguide/styleguide.css
✅ Add `outsideClickClose` prop to HoverCard to control if the HoverCard should close when a user clicks outside it
✅ Change disabled Btn to have `not-allowed` cursor
✅ Darken offwhite colour to increase contrast
✅ Remove touchend-on-all listener on HoverCard (stops iOS highlighting anything you tap)
✅ Make FormInput activate on focus
✅ Remove dead code
✅ Use new white background
=> Various component improvements

components/Btn/Btn.css, components/Checkbox/Checkbox.css, components/FormInput/FormInput.css, components/RadioGroup/Radio.css, components/Slider/Slider.css, components/Toggle/Toggle.css, globals/colours.css
- Primary is still the teal, and should only be used for call-to-actions.
- The new non-CTA colour is `--color-action`, and is a sorta graphite.
- There's also a specific colour used for focus & selection: `--color-blue-harsh`.
=> New colours!

components/DatePicker/DatePicker.css
=> More react-day-picker woes

components/Btn/Btn.css, components/Btn/Btn.js, components/__tests__/Btn-test.js, styleguide/sections/Buttons.js
=> Updated CTA styles

components/FormInput/FormInput.css, components/FormInput/FormInput.js, components/MaskedFormInput/MaskedFormInput.js, styleguide/sections/Forms.js
• Cleanup component, simplify CSS
• Use text cursor when hovering the label
• Add focus & blur methods
• Cleanup examples on styleguide
=> Refactor FormInput

components/Icon/Icon.css, components/Icon/icons.js, components/Icon/icons/podLong.svg, components/Icon/icons/podMixed.svg, components/Icon/icons/podShort.svg, globals/colours.css, styleguide/sections/Colours.js, styleguide/styleguide.css
1. Pod icons:
1. `pod_short`
2. `pod_long`
3. `pod_mixed`
2. Pod colours:
1. Long pods: `--color-aubergine`
2. Short pods: `--color-gold`
=> Pods support

globals/colours.css, styleguide/sections/Colours.js, styleguide/styleguide.css
=> Add missing pact brand colours

components/Btn/Btn.css, globals/modifiers.css
Super simple PR for making CTA buttons look correct and adding modifiers for filling icons.
=> Made CTA buttons closer to mockups

globals/typography.css
=> Removed :link selector on .whitelink which breaks the build

components/Toggle/Toggle.js
Make it an uncontrolled input component
=> Add default checked to Toggle

components/Icon/Icon.css, components/Icon/icons.js, components/Icon/icons/minus.svg, components/ValueAdjuster/ValueAdjuster.css, components/ValueAdjuster/ValueAdjuster.js, styleguide/sections/Forms.js
Value adjuster component to allow development of the [gift funnel](https://trello.com/c/VyL1oTHx)
=> Value adjuster component

components/ValueAdjuster/ValueAdjuster.js, styleguide/sections/Forms.js
Didn't see the requirement for programmatic disabling until too late :cry:
=> Value adjuster now supports programmatic disabling

components/Btn/Btn.css
=> Add back link classes

app.json, package.json
The build is failing due to npm deciding to use redbox-react 1.2.5
=> Lock redbox-react version for react 0.13

components/FormInput/FormInput.css, components/RadioGroup/Radio.css, components/Toggle/Toggle.css
Fixes:
- funny radio button
- text on toggle component
- placeholder text colour
=> IE11 fixes

components/SelectableInput/SelectableInput.js
We can now use click, copy, mouseOver etc etc
=> Allow action type to be redefined

components/EmailMultiInput/EmailMultiInput.js, components/HoverCard/HoverCard.js, util/keyCodes.js
Fixes a bug in email input component.
ES6 modules ≠ CommonJS modules: https://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default/33506169#33506169
=> Export key codes as constants

components/FormInput/SharedFormInput.js
Fixes wrong `this` scope in `watchInput`.
=> Fix autofill workaround
